import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import About from "./about/about";
import Home from "./page";
import Fonction from "./Fonction/Fonction";
import Contact from "./Contact/Contact";
import Blog from "./Blog/Blog";
import SchoolVideo from "@/components/SchoolVideo/SchoolVideo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Home />
        <About />
        <Fonction />
        <SchoolVideo />
        <Blog />
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
